name = "POMDPLinter"
uuid = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
authors = ["Zachary Sunberg <sunbergzach@gmail.com> and contributors"]
version = "0.1.1"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1"
POMDPs = "0.9"

[extras]
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "POMDPs", "Random"]
